### ISSUE TITLE
Integrate a backend for the blog using node and express.

### ISSUE THREAD

**Issue by coder-KO** [DSC-IIIT-Surat/dsc-blog#7]
Since this is a basic frontend template of the blog, a backend is yet to be integrated and we want it to be integrated to an express backend using node. After integrating the backend, add proper documentation to set it up locally and for production. All the changes regarding this are to be created in the folder of the backend in the main directory.

**Comment by shree1999** [comment]
Hello I would like to work for this

**Comment by coder-KO** [comment]
Hey, Happy that you contributed but please refrain from creating direct pull requests unless you get consent from maintainers. We have mentioned this in the Contribution Guidelines in contrib.md file.
